services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: qr_admin
      POSTGRES_PASSWORD: qr_pass
      POSTGRES_DB: qr_system
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: