"""add ticket types and staff models

Revision ID: 686d458dbf9b
Revises: 829b43f9983e
Create Date: 2025-06-13 17:09:58.469225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686d458dbf9b'
down_revision: Union[str, None] = '829b43f9983e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('login_code', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_login_code'), 'staff', ['login_code'], unique=True)
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    op.create_table('staff_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('can_checkin', sa.Boolean(), nullable=True),
    sa.Column('can_revoke', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_events_id'), 'staff_events', ['id'], unique=False)
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_types_id'), 'ticket_types', ['id'], unique=False)
    op.add_column('checkin_logs', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.add_column('checkin_logs', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('checkin_logs', sa.Column('revoked_by', sa.Integer(), nullable=True))
    op.add_column('checkin_logs', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'checkin_logs', 'staff', ['revoked_by'], ['id'])
    op.create_foreign_key(None, 'checkin_logs', 'staff', ['staff_id'], ['id'])
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_type_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('holder_phone', sa.String(length=20), nullable=True))
    op.add_column('tickets', sa.Column('external_user_id', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tickets_external_user_id'), 'tickets', ['external_user_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'ticket_types', ['ticket_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_external_user_id'), table_name='tickets')
    op.drop_column('tickets', 'notes')
    op.drop_column('tickets', 'external_user_id')
    op.drop_column('tickets', 'holder_phone')
    op.drop_column('tickets', 'ticket_type_id')
    op.drop_column('events', 'is_active')
    op.drop_constraint(None, 'checkin_logs', type_='foreignkey')
    op.drop_constraint(None, 'checkin_logs', type_='foreignkey')
    op.drop_column('checkin_logs', 'revoked_at')
    op.drop_column('checkin_logs', 'revoked_by')
    op.drop_column('checkin_logs', 'is_revoked')
    op.drop_column('checkin_logs', 'staff_id')
    op.drop_index(op.f('ix_ticket_types_id'), table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index(op.f('ix_staff_events_id'), table_name='staff_events')
    op.drop_table('staff_events')
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_index(op.f('ix_staff_login_code'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
