"""add_multi_tenant_support

Revision ID: 797a3c3b3392
Revises: 686d458dbf9b
Create Date: 2025-06-16 11:50:54.474663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797a3c3b3392'
down_revision: Union[str, None] = '686d458dbf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_merchant_id'), 'api_keys', ['merchant_id'], unique=False)
    op.add_column('events', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_merchant_id'), 'events', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'events', 'merchants', ['merchant_id'], ['id'])
    op.add_column('staff', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_staff_merchant_id'), 'staff', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'staff', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_index(op.f('ix_staff_merchant_id'), table_name='staff')
    op.drop_column('staff', 'merchant_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_merchant_id'), table_name='events')
    op.drop_column('events', 'merchant_id')
    op.drop_index(op.f('ix_api_keys_merchant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
