"""add_total_quota_to_events

Revision ID: f3d914b142ed
Revises: 5b035bda1530
Create Date: 2025-06-23 08:46:36.879827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d914b142ed'
down_revision: Union[str, None] = '5b035bda1530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('total_quota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'total_quota')
    # ### end Alembic commands ###
